WebApplicationBookLoan/Models/ErrorViewModel.cs
namespace WebApplicationBookLoan.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationBookLoan/Models/Loan.cs
namespace WebApplicationBookLoan.Models
{
    public class Loan
    {
        public int Id { get; set; }
        public string LenderName { get; set; }
        public string BorrowedName { get; set; }
        public string BookName { get; set; }
        public DateTime LoanDate { get; set; } = DateTime.Now;
    }
}

WebApplicationBookLoan/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationBookLoan.Models;

namespace WebApplicationBookLoan.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationBookLoan/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationBookLoan.Data;
using WebApplicationBookLoan.Models;

namespace WebApplicationBookLoan.Controllers
{
    public class LoansController : Controller
    {
        private readonly ConnectionContext _context;

        public LoansController(ConnectionContext context)
        {
            _context = context;
        }

        // GET: Loans
        public async Task<IActionResult> Index()
        {
            if(_context.Loan != null)
            {
                return View(await _context.Loan.ToListAsync());
            }
            else
            {
                return Problem("Entity set 'ConnectionContext.Loan'  is null.");
            }
        }

        // GET: Loans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Loan == null)
            {
                return NotFound();
            }

            var loan = await _context.Loan
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }

        // GET: Loans/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Loans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LenderName,BorrowedName,BookName,LoanDate")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(loan);
        }

        // GET: Loans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Loan == null)
            {
                return NotFound();
            }

            var loan = await _context.Loan.FindAsync(id);
            if (loan == null)
            {
                return NotFound();
            }
            return View(loan);
        }

        // POST: Loans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LenderName,BorrowedName,BookName,LoanDate")] Loan loan)
        {
            if (id != loan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoanExists(loan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loan);
        }

        // GET: Loans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Loan == null)
            {
                return NotFound();
            }

            var loan = await _context.Loan
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }

        // POST: Loans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Loan == null)
            {
                return Problem("Entity set 'ConnectionContext.Loan'  is null.");
            }
            var loan = await _context.Loan.FindAsync(id);
            if (loan != null)
            {
                _context.Loan.Remove(loan);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoanExists(int id)
        {
          return (_context.Loan?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplicationBookLoan/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplicationBookLoan/Views/Loans/Create.cshtml
@model WebApplicationBookLoan.Models.Loan

@{
    ViewData["Title"] = "Create new loan";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Lender</label>
                <input asp-for="LenderName" class="form-control" />
                <span asp-validation-for="LenderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Borrowed</label>
                <input asp-for="BorrowedName" class="form-control" />
                <span asp-validation-for="BorrowedName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Book</label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
            <div style="display: flex; justify-content: space-around; padding-top: 20px">
                <div class="form-group" style="background-color: #3CB371; border-radius: 5px">
                    <input style=" color: #F0F8FF" type="submit" value="Create" class="btn btn-sucess" />
                </div>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
            </div>
            
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationBookLoan/Views/Loans/Delete.cshtml
@model WebApplicationBookLoan.Models.Loan

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Lender
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LenderName)
        </dd>
        <dt class = "col-sm-2">
            Borrowed 
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BorrowedName)
        </dd>
        <dt class = "col-sm-2">
            Book
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            Loan date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>

WebApplicationBookLoan/Views/Loans/Details.cshtml
@model WebApplicationBookLoan.Models.Loan

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Loan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Lender
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LenderName)
        </dd>
        <dt class = "col-sm-2">
            Borrowe
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BorrowedName)
        </dd>
        <dt class = "col-sm-2">
            Book
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            Loan Date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplicationBookLoan/Views/Loans/Edit.cshtml
@model WebApplicationBookLoan.Models.Loan

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="LenderName" class="control-label">Lender</label>
                <input asp-for="LenderName" class="form-control" />
                <span asp-validation-for="LenderName" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-top: 10px">
                <label asp-for="BorrowedName" class="control-label">Borrowed</label>
                <input asp-for="BorrowedName" class="form-control" />
                <span asp-validation-for="BorrowedName" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-top: 10px">
                <label asp-for="BookName" class="control-label">Book's name</label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-top: 10px">
                <label asp-for="LoanDate" class="control-label">Loan date</label>
                <input asp-for="LoanDate" class="form-control" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div style="display: flex; justify-content: space-around; padding-top: 20px">
                <div class="form-group" style="background-color: #3CB371; border-radius: 5px">
                    <input style=" color: #F0F8FF"  type="submit" value="Save" class="btn" />
                </div>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
            </div>
            
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationBookLoan/Views/Loans/Index.cshtml
@model IEnumerable<WebApplicationBookLoan.Models.Loan>

@{
    ViewData["Title"] = "Loan list";
}
<div style="display: flex; justify-content:space-between">
    <h1>@ViewData["Title"]</h1>

    <p>
        <a asp-action="Create" class="btn btn-sucess" style="background-color:#3CB371; color:#F0F8FF">Create New</a>
    </p>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LenderName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BorrowedName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LoanDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LenderName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BorrowedName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoanDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn">Edit</a> 
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn">Details</a> 
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplicationBookLoan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationBookLoan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationBookLoan.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Loans" asp-action="Index">Book's Loan</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loans" asp-action="Index">List</a>
                        </li>
                    </ul>
                </div> *@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationBookLoan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>